<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Nethereum.Contracts" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aethos.Domain\Aethos.Domain.csproj" />
    <ProjectReference Include="..\Aethos.Math.FixedPoint\Aethos.Math.FixedPoint.csproj" />
  </ItemGroup>
</Project>
