<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Aethos.Domain\Aethos.Domain.csproj" />
    <ProjectReference Include="..\Aethos.Core.Persistence\Aethos.Core.Persistence.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup><ProjectReference Include="..\Aethos.Domain\Aethos.Domain.csproj" /><ProjectReference Include="..\Aethos.Core.Persistence\Aethos.Core.Persistence.csproj" /></ItemGroup>

<ItemGroup>
  <PackageReference Include="MongoDB.Driver" />
</ItemGroup></Project>
